swagger:
  resourcePackage: com.example.ml.infra.server.resources
  title: "ML-Infra-Lite"
  description: "A lite infrastructure for ML model serving and hot-swapping."

s3:
  endpoint: "http://minio:9000"
  region: "us-east-1"
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  bucketName: "models-bucket"
